<?php

namespace Modules\Order\Http\Controllers;

use Illuminate\Http\Request;

use Illuminate\Support\Carbon;
use Modules\Order\Entities\Order;
use Illuminate\Support\Facades\DB;
use Modules\Order\Entities\Remark;
use Modules\Order\Enums\OrderEnum;
use Maatwebsite\Excel\Facades\Excel;
use Modules\CoreData\Entities\Status;
use Modules\Order\Entities\SubStatus;
use Illuminate\Support\Facades\Storage;
use Modules\Order\Jobs\ExportOrdersJob;
use Modules\Order\Service\OrderService;

use Modules\Basic\Http\Controllers\BasicController;
use Modules\Order\Exports\Order\Admin\AttemptsLogExport;
use Modules\Order\Service\AttemptsLogService;

class AttemptsLogController extends BasicController
{
    protected $service;
    protected $attemptsLogService;

    public function __construct(OrderService $Service, AttemptsLogService $attemptsLogService)
    {
        $this->middleware('auth');
        $this->middleware('admin');
        $this->attemptsLogService = $attemptsLogService;
    }

    /**
     * The index function retrieves data for the dashboard view related to attempts log.
     * 
     * @param Request request The `Request ` parameter in the `index` function is an instance
     * of the `Illuminate\Http\Request` class. It represents an HTTP request and contains information
     * about the request such as the request method, headers, and input data.
     * 
     * @return The `index` function is returning a view called `setting::log.AttemptsLog.index` with
     * the data array passed as a parameter.
     */
    public function index(Request $request)
    {
        $data = $this->attemptsLogService->indexDashboard($request,pagination:true,perPage:$this->perPage());
        return $this->getDashboardView('setting::log.AttemptsLog.index', ['data' => $data]);
    }

    /**
     * The function `export` downloads an Excel file containing attempts log data using Laravel's Excel
     * package.
     * 
     * @return The `export()` function is returning an Excel download response using Laravel Excel. It
     * is downloading an Excel file generated by the `AttemptsLogExport` class with the filename
     * 'attempts_log.xlsx'.
     */
    public function export()
    {
        return Excel::download(new AttemptsLogExport, 'validation-log.xlsx');
    }
}
