<?php

namespace Modules\Order\Enums;

use Modules\CoreData\Entities\Status;

enum OrderEnum: int
{
    /**
     * Order statuses list
     *
     * @case string
     */
    const  NEW_STATUS = Status::NEW_STATUS;
    const  PAY_PENDING_STATUS = Status::PAY_PENDING_STATUS;
    const  PENDING_STATUS = Status::PENDING_STATUS;
    const  PENDING_INVENTORY_STATUS = Status::PENDING_INVENTORY_STATUS;
    const  PREPARING_STATUS = Status::PREPARING_STATUS;
    const  SHIPPING_STATUS = Status::SHIPPING_STATUS;
    const  REJECTED_STATUS = Status::REJECTED_STATUS;
    const  COMPLETED_STATUS = Status::COMPLETED_STATUS;
    const  CANCELED_STATUS = Status::CANCELED_STATUS;
    const  REFUND_REPLACEMENT_REQUESTED_STATUS = Status::REFUND_REPLACEMENT_REQUESTED_STATUS;
    const  REFUND_REPLACEMENT_REQUESTED_REJECTED_STATUS = Status::REFUND_REPLACEMENT_REQUESTED_REJECTED_STATUS;
    const  REFUND_PROGRESSING_STATUS = Status::REFUND_PROGRESSING_STATUS;
    const  REPLACEMENT_PROGRESSING_STATUS = Status::REPLACEMENT_PROGRESSING_STATUS;
    const  REFUND_BALANCE_STATUS = Status::REFUND_BALANCE_STATUS;
    const  REFUND_STATUS = Status::REFUND_STATUS;
    const  REPLACEMENT_STATUS = Status::REPLACEMENT_STATUS;
    const  READY_STATUS = Status::READY_STATUS;
    const  ONHOLD_STATUS = Status::ONHOLD_STATUS;
    const  RETURN_BALANCE_STATUS = Status::RETURN_BALANCE_STATUS;
}
