<?php
// Copyright
declare(strict_types=1);

namespace Modules\CoreData\CodeCountry;

//todo change
final class ListCodeCountry
{
    /**
     * It returns a List Code Country
     */

    public static function list()
    {
        $payment =  collect([]);

        $payment->push(
            [
                'sort' => 'AF',
                'country_name' => 'Afghanistan',
                'phoneCode' => 93,
                'flag'=>asset('country-flag/country-af.svg'),
            ],
            [
                'sort' => 'AL',
                'country_name' => 'Albania',
                'phoneCode' => 355,
                'flag'=>asset('country-flag/country-al.svg'),
            ],
            [
                'sort' => 'DZ',
                'country_name' => 'Algeria',
                'phoneCode' => 213,
                'flag'=>asset('country-flag/country-dz.svg'),
            ],
            [
                'sort' => 'AS',
                'country_name' => 'American Samoa',
                'phoneCode' => 1684,
                'flag'=>asset('country-flag/country-as.svg'),
            ],
            [
                'sort' => 'AD',
                'country_name' => 'Andorra',
                'phoneCode' => 376,
                'flag'=>asset('country-flag/country-ad.svg'),
            ],
            [
                'sort' => 'AO',
                'country_name' => 'Angola',
                'phoneCode' => 244,
                'flag'=>asset('country-flag/country-ao.svg'),
            ],
            [
                'sort' => 'AI',
                'country_name' => 'Anguilla',
                'phoneCode' => 1264,
                'flag'=>asset('country-flag/country-ai.svg'),
            ],
            [
                'sort' => 'AQ',
                'country_name' => 'Antarctica',
                'phoneCode' => 0,
                'flag'=>asset('country-flag/country-aq.svg'),
            ],
            [
                'sort' => 'AG',
                'country_name' => 'Antigua And Barbuda',
                'phoneCode' => 1268,
                'flag'=>asset('country-flag/country-ag.svg'),
            ],
            [
                'sort' => 'AR',
                'country_name' => 'Argentina',
                'phoneCode' => 54,
                'flag'=>asset('country-flag/country-ar.svg'),
            ],
            [
                'sort' => 'AM',
                'country_name' => 'Armenia',
                'phoneCode' => 374,
                'flag'=>asset('country-flag/country-am.svg'),
            ],
            [
                'sort' => 'AW',
                'country_name' => 'Aruba',
                'phoneCode' => 297,
                'flag'=>asset('country-flag/country-aw.svg'),
            ],
            [
                'sort' => 'AU',
                'country_name' => 'Australia',
                'phoneCode' => 61,
                'flag'=>asset('country-flag/country-au.svg'),
            ],
            [
                'sort' => 'AT',
                'country_name' => 'Austria',
                'phoneCode' => 43,
                'flag'=>asset('country-flag/country-at.svg'),
            ],
            [
                'sort' => 'AZ',
                'country_name' => 'Azerbaijan',
                'phoneCode' => 994,
                'flag'=>asset('country-flag/country-az.svg'),
            ],
            [
                'sort' => 'BS',
                'country_name' => 'Bahamas The',
                'phoneCode' => 1242,
                'flag'=>asset('country-flag/country-bs.svg'),
            ],
            [
                'sort' => 'BH',
                'country_name' => 'Bahrain',
                'phoneCode' => 973,
                'flag'=>asset('country-flag/country-bh.svg'),
            ],
            [
                'sort' => 'BD',
                'country_name' => 'Bangladesh',
                'phoneCode' => 880,
                'flag'=>asset('country-flag/country-bd.svg'),
            ],
            [
                'sort' => 'BB',
                'country_name' => 'Barbados',
                'phoneCode' => 1246,
                'flag'=>asset('country-flag/country-bb.svg'),
            ],
            [
                'sort' => 'BY',
                'country_name' => 'Belarus',
                'phoneCode' => 375,
                'flag'=>asset('country-flag/country-by.svg'),
            ],
            [
                'sort' => 'BE',
                'country_name' => 'Belgium',
                'phoneCode' => 32,
                'flag'=>asset('country-flag/country-be.svg'),
            ],
            [
                'sort' => 'BZ',
                'country_name' => 'Belize',
                'phoneCode' => 501,
                'flag'=>asset('country-flag/country-bz.svg'),
            ],
            [
                'sort' => 'BJ',
                'country_name' => 'Benin',
                'phoneCode' => 229,
                'flag'=>asset('country-flag/country-bj.svg'),
            ],
            [
                'sort' => 'BM',
                'country_name' => 'Bermuda',
                'phoneCode' => 1441,
                'flag'=>asset('country-flag/country-bm.svg'),
            ],
            [
                'sort' => 'BT',
                'country_name' => 'Bhutan',
                'phoneCode' => 975,
                'flag'=>asset('country-flag/country-bt.svg'),
            ],
            [
                'sort' => 'BO',
                'country_name' => 'Bolivia',
                'phoneCode' => 591,
                'flag'=>asset('country-flag/country-bo.svg'),
            ],
            [
                'sort' => 'BA',
                'country_name' => 'Bosnia and Herzegovina',
                'phoneCode' => 387,
                'flag'=>asset('country-flag/country-ba.svg'),
            ],
            [
                'sort' => 'BW',
                'country_name' => 'Botswana',
                'phoneCode' => 267,
                'flag'=>asset('country-flag/country-bw.svg'),
            ],
            [
                'sort' => 'BV',
                'country_name' => 'Bouvet Island',
                'phoneCode' => 0,
                'flag'=>asset('country-flag/country-bv.svg'),
            ],
            [
                'sort' => 'BR',
                'country_name' => 'Brazil',
                'phoneCode' => 55,
                'flag'=>asset('country-flag/country-br.svg'),
            ],
            [
                'sort' => 'IO',
                'country_name' => 'British Indian Ocean Territory',
                'phoneCode' => 246,
                'flag'=>asset('country-flag/country-io.svg'),
            ],
            [
                'sort' => 'BN',
                'country_name' => 'Brunei',
                'phoneCode' => 673,
                'flag'=>asset('country-flag/country-bn.svg'),
            ],
            [
                'sort' => 'BG',
                'country_name' => 'Bulgaria',
                'phoneCode' => 359,
                'flag'=>asset('country-flag/country-bg.svg'),
            ],
            [
                'sort' => 'BF',
                'country_name' => 'Burkina Faso',
                'phoneCode' => 226,
                'flag'=>asset('country-flag/country-bf.svg'),
            ],
            [
                'sort' => 'BI',
                'country_name' => 'Burundi',
                'phoneCode' => 257,
                'flag'=>asset('country-flag/country-bi.svg'),
            ],
            [
                'sort' => 'KH',
                'country_name' => 'Cambodia',
                'phoneCode' => 855,
                'flag'=>asset('country-flag/country-kh.svg'),
            ],
            [
                'sort' => 'CM',
                'country_name' => 'Cameroon',
                'phoneCode' => 237,
                'flag'=>asset('country-flag/country-cm.svg'),
            ],
            [
                'sort' => 'CA',
                'country_name' => 'Canada',
                'phoneCode' => 1,
                'flag'=>asset('country-flag/country-ca.svg'),
            ],
            [
                'sort' => 'CV',
                'country_name' => 'Cape Verde',
                'phoneCode' => 238,
                'flag'=>asset('country-flag/country-cv.svg'),
            ],
            [
                'sort' => 'KY',
                'country_name' => 'Cayman Islands',
                'phoneCode' => 1345,
                'flag'=>asset('country-flag/country-ky.svg'),
            ],
            [
                'sort' => 'CF',
                'country_name' => 'Central African Republic',
                'phoneCode' => 236,
                'flag'=>asset('country-flag/country-cf.svg'),
            ],
            [
                'sort' => 'TD',
                'country_name' => 'Chad',
                'phoneCode' => 235,
                'flag'=>asset('country-flag/country-td.svg'),
            ],
            [
                'sort' => 'CL',
                'country_name' => 'Chile',
                'phoneCode' => 56,
                'flag'=>asset('country-flag/country-cl.svg'),
            ],
            [
                'sort' => 'CN',
                'country_name' => 'China',
                'phoneCode' => 86,
                'flag'=>asset('country-flag/country-cn.svg'),
            ],
            [
                'sort' => 'CX',
                'country_name' => 'Christmas Island',
                'phoneCode' => 61,
                'flag'=>asset('country-flag/country-cx.svg'),
            ],
            [
                'sort' => 'CC',
                'country_name' => 'Cocos (Keeling) Islands',
                'phoneCode' => 672,
                'flag'=>asset('country-flag/country-cc.svg'),
            ],
            [
                'sort' => 'CO',
                'country_name' => 'Colombia',
                'phoneCode' => 57,
                'flag'=>asset('country-flag/country-co.svg'),
            ],
            [
                'sort' => 'KM',
                'country_name' => 'Comoros',
                'phoneCode' => 269,
                'flag'=>asset('country-flag/country-km.svg'),
            ],
            [
                'sort' => 'CG',
                'country_name' => 'Republic Of The Congo',
                'phoneCode' => 242,
                'flag'=>asset('country-flag/country-cg.svg'),
            ],
            [
                'sort' => 'CD',
                'country_name' => 'Democratic Republic Of The Congo',
                'phoneCode' => 242,
                'flag'=>asset('country-flag/country-cd.svg'),
            ],
            [
                'sort' => 'CK',
                'country_name' => 'Cook Islands',
                'phoneCode' => 682,
                'flag'=>asset('country-flag/country-ck.svg'),
            ],
            [
                'sort' => 'CR',
                'country_name' => 'Costa Rica',
                'phoneCode' => 506,
                'flag'=>asset('country-flag/country-cr.svg'),
            ],
            [
                'sort' => 'CI',
                'country_name' => 'Cote D Ivoire (Ivory Coast)',
                'phoneCode' => 225,
                'flag'=>asset('country-flag/country-ci.svg'),
            ],
            [
                'sort' => 'HR',
                'country_name' => 'Croatia (Hrvatska)',
                'phoneCode' => 385,
                'flag'=>asset('country-flag/country-hr.svg'),
            ],
            [
                'sort' => 'CU',
                'country_name' => 'Cuba',
                'phoneCode' => 53,
                'flag'=>asset('country-flag/country-cu.svg'),
            ],
            [
                'sort' => 'CY',
                'country_name' => 'Cyprus',
                'phoneCode' => 357,
                'flag'=>asset('country-flag/country-cy.svg'),
            ],
            [
                'sort' => 'CZ',
                'country_name' => 'Czech Republic',
                'phoneCode' => 420,
                'flag'=>asset('country-flag/country-cz.svg'),
            ],
            [
                'sort' => 'DK',
                'country_name' => 'Denmark',
                'phoneCode' => 45,
                'flag'=>asset('country-flag/country-dk.svg'),
            ],
            [
                'sort' => 'DJ',
                'country_name' => 'Djibouti',
                'phoneCode' => 253,
                'flag'=>asset('country-flag/country-dj.svg'),
            ],
            [
                'sort' => 'DM',
                'country_name' => 'Dominica',
                'phoneCode' => 1767,
                'flag'=>asset('country-flag/country-dm.svg'),
            ],
            [
                'sort' => 'DO',
                'country_name' => 'Dominican Republic',
                'phoneCode' => 1809,
                'flag'=>asset('country-flag/country-do.svg'),
            ],
            [
                'sort' => 'TP',
                'country_name' => 'East Timor',
                'phoneCode' => 670,
                'flag'=>asset('country-flag/country-tp.svg'),
            ],
            [
                'sort' => 'EC',
                'country_name' => 'Ecuador',
                'phoneCode' => 593,
                'flag'=>asset('country-flag/country-ec.svg'),
            ],
            [
                'sort' => 'EG',
                'country_name' => 'Egypt',
                'phoneCode' => 20,
                'flag'=>asset('country-flag/country-eg.svg'),
            ],
            [
                'sort' => 'SV',
                'country_name' => 'El Salvador',
                'phoneCode' => 503,
                'flag'=>asset('country-flag/country-sv.svg'),
            ],
            [
                'sort' => 'GQ',
                'country_name' => 'Equatorial Guinea',
                'phoneCode' => 240,
                'flag'=>asset('country-flag/country-gq.svg'),
            ],
            [
                'sort' => 'ER',
                'country_name' => 'Eritrea',
                'phoneCode' => 291,
                'flag'=>asset('country-flag/country-er.svg'),
            ],
            [
                'sort' => 'EE',
                'country_name' => 'Estonia',
                'phoneCode' => 372,
                'flag'=>asset('country-flag/country-ee.svg'),
            ],
            [
                'sort' => 'ET',
                'country_name' => 'Ethiopia',
                'phoneCode' => 251,
                'flag'=>asset('country-flag/country-et.svg'),
            ],
            [
                'sort' => 'XA',
                'country_name' => 'External Territories of Australia',
                'phoneCode' => 61,
                'flag'=>asset('country-flag/country-xa.svg'),
            ],
            [
                'sort' => 'FK',
                'country_name' => 'Falkland Islands',
                'phoneCode' => 500,
                'flag'=>asset('country-flag/country-fk.svg'),
            ],
            [
                'sort' => 'FO',
                'country_name' => 'Faroe Islands',
                'phoneCode' => 298,
                'flag'=>asset('country-flag/country-fo.svg'),
            ],
            [
                'sort' => 'FJ',
                'country_name' => 'Fiji Islands',
                'phoneCode' => 679,
                'flag'=>asset('country-flag/country-fj.svg'),
            ],
            [
                'sort' => 'FI',
                'country_name' => 'Finland',
                'phoneCode' => 358,
                'flag'=>asset('country-flag/country-fi.svg'),
            ],
            [
                'sort' => 'FR',
                'country_name' => 'France',
                'phoneCode' => 33,
                'flag'=>asset('country-flag/country-fr.svg'),
            ],
            [
                'sort' => 'GF',
                'country_name' => 'French Guiana',
                'phoneCode' => 594,
                'flag'=>asset('country-flag/country-gf.svg'),
            ],
            [
                'sort' => 'PF',
                'country_name' => 'French Polynesia',
                'phoneCode' => 689,
                'flag'=>asset('country-flag/country-pf.svg'),
            ],
            [
                'sort' => 'TF',
                'country_name' => 'French Southern Territories',
                'phoneCode' => 0,
                'flag'=>asset('country-flag/country-tf.svg'),
            ],
            [
                'sort' => 'GA',
                'country_name' => 'Gabon',
                'phoneCode' => 241,
                'flag'=>asset('country-flag/country-ga.svg'),
            ],
            [
                'sort' => 'GM',
                'country_name' => 'Gambia The',
                'phoneCode' => 220,
                'flag'=>asset('country-flag/country-gm.svg'),
            ],
            [
                'sort' => 'GE',
                'country_name' => 'Georgia',
                'phoneCode' => 995,
                'flag'=>asset('country-flag/country-ge.svg'),
            ],
            [
                'sort' => 'DE',
                'country_name' => 'Germany',
                'phoneCode' => 49,
                'flag'=>asset('country-flag/country-de.svg'),
            ],
            [
                'sort' => 'GH',
                'country_name' => 'Ghana',
                'phoneCode' => 233,
                'flag'=>asset('country-flag/country-gh.svg'),
            ],
            [
                'sort' => 'GI',
                'country_name' => 'Gibraltar',
                'phoneCode' => 350,
                'flag'=>asset('country-flag/country-gi.svg'),
            ],
            [
                'sort' => 'GR',
                'country_name' => 'Greece',
                'phoneCode' => 30,
                'flag'=>asset('country-flag/country-gr.svg'),
            ],
            [
                'sort' => 'GL',
                'country_name' => 'Greenland',
                'phoneCode' => 299,
                'flag'=>asset('country-flag/country-gl.svg'),
            ],
            [
                'sort' => 'GD',
                'country_name' => 'Grenada',
                'phoneCode' => 1473,
                'flag'=>asset('country-flag/country-gd.svg'),
            ],
            [
                'sort' => 'GP',
                'country_name' => 'Guadeloupe',
                'phoneCode' => 590,
                'flag'=>asset('country-flag/country-gp.svg'),
            ],
            [
                'sort' => 'GU',
                'country_name' => 'Guam',
                'phoneCode' => 1671,
                'flag'=>asset('country-flag/country-gu.svg'),
            ],
            [
                'sort' => 'GT',
                'country_name' => 'Guatemala',
                'phoneCode' => 502,
                'flag'=>asset('country-flag/country-gt.svg'),
            ],
            [
                'sort' => 'XU',
                'country_name' => 'Guernsey and Alderney',
                'phoneCode' => 44,
                'flag'=>asset('country-flag/country-xu.svg'),
            ],
            [
                'sort' => 'GN',
                'country_name' => 'Guinea',
                'phoneCode' => 224,
                'flag'=>asset('country-flag/country-gn.svg'),
            ],
            [
                'sort' => 'GW',
                'country_name' => 'Guinea-Bissau',
                'phoneCode' => 245,
                'flag'=>asset('country-flag/country-gw.svg'),
            ],
            [
                'sort' => 'GY',
                'country_name' => 'Guyana',
                'phoneCode' => 592,
                'flag'=>asset('country-flag/country-gy.svg'),
            ],
            [
                'sort' => 'HT',
                'country_name' => 'Haiti',
                'phoneCode' => 509,
                'flag'=>asset('country-flag/country-ht.svg'),
            ],
            [
                'sort' => 'HM',
                'country_name' => 'Heard and McDonald Islands',
                'phoneCode' => 0,
                'flag'=>asset('country-flag/country-hm.svg'),
            ],
            [
                'sort' => 'HN',
                'country_name' => 'Honduras',
                'phoneCode' => 504,
                'flag'=>asset('country-flag/country-hn.svg'),
            ],
            [
                'sort' => 'HK',
                'country_name' => 'Hong Kong S.A.R.',
                'phoneCode' => 852,
                'flag'=>asset('country-flag/country-hk.svg'),
            ],
            [
                'sort' => 'HU',
                'country_name' => 'Hungary',
                'phoneCode' => 36,
                'flag'=>asset('country-flag/country-hu.svg'),
            ],
            [
                'sort' => 'IS',
                'country_name' => 'Iceland',
                'phoneCode' => 354,
                'flag'=>asset('country-flag/country-is.svg'),
            ],
            [
                'sort' => 'IN',
                'country_name' => 'India',
                'phoneCode' => 91,
                'flag'=>asset('country-flag/country-in.svg'),
            ],
            [
                'sort' => 'ID',
                'country_name' => 'Indonesia',
                'phoneCode' => 62,
                'flag'=>asset('country-flag/country-id.svg'),
            ],
            [
                'sort' => 'IR',
                'country_name' => 'Iran',
                'phoneCode' => 98,
                'flag'=>asset('country-flag/country-ir.svg'),
            ],
            [
                'sort' => 'IQ',
                'country_name' => 'Iraq',
                'phoneCode' => 964,
                'flag'=>asset('country-flag/country-rq.svg'),
            ],
            [
                'sort' => 'IE',
                'country_name' => 'Ireland',
                'phoneCode' => 353,
                'flag'=>asset('country-flag/country-ie.svg'),
            ],
            [
                'sort' => 'IL',
                'country_name' => 'Israel',
                'phoneCode' => 972,
                'flag'=>asset('country-flag/country-il.svg'),
            ],
            [
                'sort' => 'IT',
                'country_name' => 'Italy',
                'phoneCode' => 39,
                'flag'=>asset('country-flag/country-it.svg'),
            ],
            [
                'sort' => 'JM',
                'country_name' => 'Jamaica',
                'phoneCode' => 1876,
                'flag'=>asset('country-flag/country-jm.svg'),
            ],
            [
                'sort' => 'JP',
                'country_name' => 'Japan',
                'phoneCode' => 81,
                'flag'=>asset('country-flag/country-jp.svg'),
            ],
            [
                'sort' => 'XJ',
                'country_name' => 'Jersey',
                'phoneCode' => 44,
                'flag'=>asset('country-flag/country-xj.svg'),
            ],
            [
                'sort' => 'JO',
                'country_name' => 'Jordan',
                'phoneCode' => 962,
                'flag'=>asset('country-flag/country-jo.svg'),
            ],
            [
                'sort' => 'KZ',
                'country_name' => 'Kazakhstan',
                'phoneCode' => 7,
                'flag'=>asset('country-flag/country-kz.svg'),
            ],
            [
                'sort' => 'KE',
                'country_name' => 'Kenya',
                'phoneCode' => 254,
                'flag'=>asset('country-flag/country-ke.svg'),
            ],
            [
                'sort' => 'KI',
                'country_name' => 'Kiribati',
                'phoneCode' => 686,
                'flag'=>asset('country-flag/country-ki.svg'),
            ],
            [
                'sort' => 'KP',
                'country_name' => 'Korea North',
                'phoneCode' => 850,
                'flag'=>asset('country-flag/country-kp.svg'),
            ],
            [
                'sort' => 'KR',
                'country_name' => 'Korea South',
                'phoneCode' => 82,
                'flag'=>asset('country-flag/country-kr.svg'),
            ],
            [
                'sort' => 'KW',
                'country_name' => 'Kuwait',
                'phoneCode' => 965,
                'flag'=>asset('country-flag/country-kw.svg'),
            ],
            [
                'sort' => 'KG',
                'country_name' => 'Kyrgyzstan',
                'phoneCode' => 996,
                'flag'=>asset('country-flag/country-kg.svg'),
            ],
            [
                'sort' => 'LA',
                'country_name' => 'Laos',
                'phoneCode' => 856,
                'flag'=>asset('country-flag/country-la.svg'),
            ],
            [
                'sort' => 'LV',
                'country_name' => 'Latvia',
                'phoneCode' => 371,
                'flag'=>asset('country-flag/country-lv.svg'),
            ],
            [
                'sort' => 'LB',
                'country_name' => 'Lebanon',
                'phoneCode' => 961,
                'flag'=>asset('country-flag/country-lb.svg'),
            ],
            [
                'sort' => 'LS',
                'country_name' => 'Lesotho',
                'phoneCode' => 266,
                'flag'=>asset('country-flag/country-ls.svg'),
            ],
            [
                'sort' => 'LR',
                'country_name' => 'Liberia',
                'phoneCode' => 231,
                'flag'=>asset('country-flag/country-lr.svg'),
            ],
            [
                'sort' => 'LY',
                'country_name' => 'Libya',
                'phoneCode' => 218,
                'flag'=>asset('country-flag/country-ly.svg'),
            ],
            [
                'sort' => 'LI',
                'country_name' => 'Liechtenstein',
                'phoneCode' => 423,
                'flag'=>asset('country-flag/country-li.svg'),
            ],
            [
                'sort' => 'LT',
                'country_name' => 'Lithuania',
                'phoneCode' => 370,
                'flag'=>asset('country-flag/country-lt.svg'),
            ],
            [
                'sort' => 'LU',
                'country_name' => 'Luxembourg',
                'phoneCode' => 352,
                'flag'=>asset('country-flag/country-lu.svg'),
            ],
            [
                'sort' => 'MO',
                'country_name' => 'Macau S.A.R.',
                'phoneCode' => 853,
                'flag'=>asset('country-flag/country-mo.svg'),
            ],
            [
                'sort' => 'MK',
                'country_name' => 'Macedonia',
                'phoneCode' => 389,
                'flag'=>asset('country-flag/country-mk.svg'),
            ],
            [
                'sort' => 'MG',
                'country_name' => 'Madagascar',
                'phoneCode' => 261,
                'flag'=>asset('country-flag/country-mg.svg'),
            ],
            [
                'sort' => 'MW',
                'country_name' => 'Malawi',
                'phoneCode' => 265,
                'flag'=>asset('country-flag/country-mw.svg'),
            ],
            [
                'sort' => 'MY',
                'country_name' => 'Malaysia',
                'phoneCode' => 60,
                'flag'=>asset('country-flag/country-my.svg'),
            ],
            [
                'sort' => 'MV',
                'country_name' => 'Maldives',
                'phoneCode' => 960,
                'flag'=>asset('country-flag/country-mv.svg'),
            ],
            [
                'sort' => 'ML',
                'country_name' => 'Mali',
                'phoneCode' => 223,
                'flag'=>asset('country-flag/country-ml.svg'),
            ],
            [
                'sort' => 'MT',
                'country_name' => 'Malta',
                'phoneCode' => 356,
                'flag'=>asset('country-flag/country-mt.svg'),
            ],
            [
                'sort' => 'XM',
                'country_name' => 'Man (Isle of)',
                'phoneCode' => 44,
                'flag'=>asset('country-flag/country-xm.svg'),
            ],
            [
                'sort' => 'MH',
                'country_name' => 'Marshall Islands',
                'phoneCode' => 692,
                'flag'=>asset('country-flag/country-mh.svg'),
            ],
            [
                'sort' => 'MQ',
                'country_name' => 'Martinique',
                'phoneCode' => 596,
                'flag'=>asset('country-flag/country-mq.svg'),
            ],
            [
                'sort' => 'MR',
                'country_name' => 'Mauritania',
                'phoneCode' => 222,
                'flag'=>asset('country-flag/country-mr.svg'),
            ],
            [
                'sort' => 'MU',
                'country_name' => 'Mauritius',
                'phoneCode' => 230,
                'flag'=>asset('country-flag/country-mu.svg'),
            ],
            [
                'sort' => 'YT',
                'country_name' => 'Mayotte',
                'phoneCode' => 269,
                'flag'=>asset('country-flag/country-yt.svg'),
            ],
            [
                'sort' => 'MX',
                'country_name' => 'Mexico',
                'phoneCode' => 52,
                'flag'=>asset('country-flag/country-mx.svg'),
            ],
            [
                'sort' => 'FM',
                'country_name' => 'Micronesia',
                'phoneCode' => 691,
                'flag'=>asset('country-flag/country-fm.svg'),
            ],
            [
                'sort' => 'MD',
                'country_name' => 'Moldova',
                'phoneCode' => 373,
                'flag'=>asset('country-flag/country-md.svg'),
            ],
            [
                'sort' => 'MC',
                'country_name' => 'Monaco',
                'phoneCode' => 377,
                'flag'=>asset('country-flag/country-mc.svg'),
            ],
            [
                'sort' => 'MN',
                'country_name' => 'Mongolia',
                'phoneCode' => 976,
                'flag'=>asset('country-flag/country-mn.svg'),
            ],
            [
                'sort' => 'MS',
                'country_name' => 'Montserrat',
                'phoneCode' => 1664,
                'flag'=>asset('country-flag/country-ms.svg'),
            ],
            [
                'sort' => 'MA',
                'country_name' => 'Morocco',
                'phoneCode' => 212,
                'flag'=>asset('country-flag/country-ma.svg'),
            ],
            [
                'sort' => 'MZ',
                'country_name' => 'Mozambique',
                'phoneCode' => 258,
                'flag'=>asset('country-flag/country-mz.svg'),
            ],
            [
                'sort' => 'MM',
                'country_name' => 'Myanmar',
                'phoneCode' => 95,
                'flag'=>asset('country-flag/country-mm.svg'),
            ],
            [
                'sort' => 'NA',
                'country_name' => 'Namibia',
                'phoneCode' => 264,
                'flag'=>asset('country-flag/country-na.svg'),
            ],
            [
                'sort' => 'NR',
                'country_name' => 'Nauru',
                'phoneCode' => 674,
                'flag'=>asset('country-flag/country-nr.svg'),
            ],
            [
                'sort' => 'NP',
                'country_name' => 'Nepal',
                'phoneCode' => 977,
                'flag'=>asset('country-flag/country-np.svg'),
            ],
            [
                'sort' => 'AN',
                'country_name' => 'Netherlands Antilles',
                'phoneCode' => 599,
                'flag'=>asset('country-flag/country-an.svg'),
            ],
            [
                'sort' => 'NL',
                'country_name' => 'Netherlands The',
                'phoneCode' => 31,
                'flag'=>asset('country-flag/country-nl.svg'),
            ],
            [
                'sort' => 'NC',
                'country_name' => 'New Caledonia',
                'phoneCode' => 687,
                'flag'=>asset('country-flag/country-nc.svg'),
            ],
            [
                'sort' => 'NZ',
                'country_name' => 'New Zealand',
                'phoneCode' => 64,
                'flag'=>asset('country-flag/country-nz.svg'),
            ],
            [
                'sort' => 'NI',
                'country_name' => 'Nicaragua',
                'phoneCode' => 505,
                'flag'=>asset('country-flag/country-ni.svg'),
            ],
            [
                'sort' => 'NE',
                'country_name' => 'Niger',
                'phoneCode' => 227,
                'flag'=>asset('country-flag/country-ne.svg'),
            ],
            [
                'sort' => 'NG',
                'country_name' => 'Nigeria',
                'phoneCode' => 234,
                'flag'=>asset('country-flag/country-ng.svg'),
            ],
            [
                'sort' => 'NU',
                'country_name' => 'Niue',
                'phoneCode' => 683,
                'flag'=>asset('country-flag/country-nu.svg'),
            ],
            [
                'sort' => 'NF',
                'country_name' => 'Norfolk Island',
                'phoneCode' => 672,
                'flag'=>asset('country-flag/country-nf.svg'),
            ],
            [
                'sort' => 'MP',
                'country_name' => 'Northern Mariana Islands',
                'phoneCode' => 1670,
                'flag'=>asset('country-flag/country-mp.svg'),
            ],
            [
                'sort' => 'NO',
                'country_name' => 'Norway',
                'phoneCode' => 47,
                'flag'=>asset('country-flag/country-no.svg'),
            ],
            [
                'sort' => 'OM',
                'country_name' => 'Oman',
                'phoneCode' => 968,
                'flag'=>asset('country-flag/country-om.svg'),
            ],
            [
                'sort' => 'PK',
                'country_name' => 'Pakistan',
                'phoneCode' => 92,
                'flag'=>asset('country-flag/country-pk.svg'),
            ],
            [
                'sort' => 'PW',
                'country_name' => 'Palau',
                'phoneCode' => 680,
                'flag'=>asset('country-flag/country-pw.svg'),
            ],
            [
                'sort' => 'PS',
                'country_name' => 'Palestinian Territory Occupied',
                'phoneCode' => 970,
                'flag'=>asset('country-flag/country-ps.svg'),
            ],
            [
                'sort' => 'PA',
                'country_name' => 'Panama',
                'phoneCode' => 507,
                'flag'=>asset('country-flag/country-pa.svg'),
            ],
            [
                'sort' => 'PG',
                'country_name' => 'Papua new Guinea',
                'phoneCode' => 675,
                'flag'=>asset('country-flag/country-pg.svg'),
            ],
            [
                'sort' => 'PY',
                'country_name' => 'Paraguay',
                'phoneCode' => 595,
                'flag'=>asset('country-flag/country-py.svg'),
            ],
            [
                'sort' => 'PE',
                'country_name' => 'Peru',
                'phoneCode' => 51,
                'flag'=>asset('country-flag/country-pe.svg'),
            ],
            [
                'sort' => 'PH',
                'country_name' => 'Philippines',
                'phoneCode' => 63,
                'flag'=>asset('country-flag/country-ph.svg'),
            ],
            [
                'sort' => 'PN',
                'country_name' => 'Pitcairn Island',
                'phoneCode' => 0,
                'flag'=>asset('country-flag/country-pn.svg'),
            ],
            [
                'sort' => 'PL',
                'country_name' => 'Poland',
                'phoneCode' => 48,
                'flag'=>asset('country-flag/country-pl.svg'),
            ],
            [
                'sort' => 'PT',
                'country_name' => 'Portugal',
                'phoneCode' => 351,
                'flag'=>asset('country-flag/country-pt.svg'),
            ],
            [
                'sort' => 'PR',
                'country_name' => 'Puerto Rico',
                'phoneCode' => 1787,
                'flag'=>asset('country-flag/country-pr.svg'),
            ],
            [
                'sort' => 'QA',
                'country_name' => 'Qatar',
                'phoneCode' => 974,
                'flag'=>asset('country-flag/country-qa.svg'),
            ],
            [
                'sort' => 'RE',
                'country_name' => 'Reunion',
                'phoneCode' => 262,
                'flag'=>asset('country-flag/country-re.svg'),
            ],
            [
                'sort' => 'RO',
                'country_name' => 'Romania',
                'phoneCode' => 40,
                'flag'=>asset('country-flag/country-ro.svg'),
            ],
            [
                'sort' => 'RU',
                'country_name' => 'Russia',
                'phoneCode' => 70,
                'flag'=>asset('country-flag/country-ru.svg'),
            ],
            [
                'sort' => 'RW',
                'country_name' => 'Rwanda',
                'phoneCode' => 250,
                'flag'=>asset('country-flag/country-rw.svg'),
            ],
            [
                'sort' => 'SH',
                'country_name' => 'Saint Helena',
                'phoneCode' => 290,
                'flag'=>asset('country-flag/country-sh.svg'),
            ],
            [
                'sort' => 'KN',
                'country_name' => 'Saint Kitts And Nevis',
                'phoneCode' => 1869,
                'flag'=>asset('country-flag/country-kn.svg'),
            ],
            [
                'sort' => 'LC',
                'country_name' => 'Saint Lucia',
                'phoneCode' => 1758,
                'flag'=>asset('country-flag/country-lc.svg'),
            ],
            [
                'sort' => 'PM',
                'country_name' => 'Saint Pierre and Miquelon',
                'phoneCode' => 508,
                'flag'=>asset('country-flag/country-pm.svg'),
            ],
            [
                'sort' => 'VC',
                'country_name' => 'Saint Vincent And The Grenadines',
                'phoneCode' => 1784,
                'flag'=>asset('country-flag/country-vc.svg'),
            ],
            [
                'sort' => 'WS',
                'country_name' => 'Samoa',
                'phoneCode' => 684,
                'flag'=>asset('country-flag/country-ws.svg'),
            ],
            [
                'sort' => 'SM',
                'country_name' => 'San Marino',
                'phoneCode' => 378,
                'flag'=>asset('country-flag/country-sm.svg'),
            ],
            [
                'sort' => 'ST',
                'country_name' => 'Sao Tome and Principe',
                'phoneCode' => 239,
                'flag'=>asset('country-flag/country-st.svg'),
            ],
            [
                'sort' => 'SA',
                'country_name' => 'Saudi Arabia',
                'phoneCode' => 966,
                'flag'=>asset('country-flag/country-sa.svg'),
            ],
            [
                'sort' => 'SN',
                'country_name' => 'Senegal',
                'phoneCode' => 221,
                'flag'=>asset('country-flag/country-sn.svg'),
            ],
            [
                'sort' => 'RS',
                'country_name' => 'Serbia',
                'phoneCode' => 381,
                'flag'=>asset('country-flag/country-rs.svg'),
            ],
            [
                'sort' => 'SC',
                'country_name' => 'Seychelles',
                'phoneCode' => 248,
                'flag'=>asset('country-flag/country-sc.svg'),
            ],
            [
                'sort' => 'SL',
                'country_name' => 'Sierra Leone',
                'phoneCode' => 232,
                'flag'=>asset('country-flag/country-sl.svg'),
            ],
            [
                'sort' => 'SG',
                'country_name' => 'Singapore',
                'phoneCode' => 65,
                'flag'=>asset('country-flag/country-sg.svg'),
            ],
            [
                'sort' => 'SK',
                'country_name' => 'Slovakia',
                'phoneCode' => 421,
                'flag'=>asset('country-flag/country-sk.svg'),
            ],
            [
                'sort' => 'SI',
                'country_name' => 'Slovenia',
                'phoneCode' => 386,
                'flag'=>asset('country-flag/country-si.svg'),
            ],
            [
                'sort' => 'XG',
                'country_name' => 'Smaller Territories of the UK',
                'phoneCode' => 44,
                'flag'=>asset('country-flag/country-xg.svg'),
            ],
            [
                'sort' => 'SB',
                'country_name' => 'Solomon Islands',
                'phoneCode' => 677,
                'flag'=>asset('country-flag/country-sb.svg'),
            ],
            [
                'sort' => 'SO',
                'country_name' => 'Somalia',
                'phoneCode' => 252,
                'flag'=>asset('country-flag/country-so.svg'),
            ],
            [
                'sort' => 'ZA',
                'country_name' => 'South Africa',
                'phoneCode' => 27,
                'flag'=>asset('country-flag/country-za.svg'),
            ],
            [
                'sort' => 'GS',
                'country_name' => 'South Georgia',
                'phoneCode' => 0,
                'flag'=>asset('country-flag/country-gs.svg'),
            ],
            [
                'sort' => 'SS',
                'country_name' => 'South Sudan',
                'phoneCode' => 211,
                'flag'=>asset('country-flag/country-ss.svg'),
            ],
            [
                'sort' => 'ES',
                'country_name' => 'Spain',
                'phoneCode' => 34,
                'flag'=>asset('country-flag/country-es.svg'),
            ],
            [
                'sort' => 'LK',
                'country_name' => 'Sri Lanka',
                'phoneCode' => 94,
                'flag'=>asset('country-flag/country-lk.svg'),
            ],
            [
                'sort' => 'SD',
                'country_name' => 'Sudan',
                'phoneCode' => 249,
                'flag'=>asset('country-flag/country-sd.svg'),
            ],
            [
                'sort' => 'SR',
                'country_name' => 'Suricountry_name',
                'phoneCode' => 597,
                'flag'=>asset('country-flag/country-sr.svg'),
            ],
            [
                'sort' => 'SJ',
                'country_name' => 'Svalbard And Jan Mayen Islands',
                'phoneCode' => 47,
                'flag'=>asset('country-flag/country-sj.svg'),
            ],
            [
                'sort' => 'SZ',
                'country_name' => 'Swaziland',
                'phoneCode' => 268,
                'flag'=>asset('country-flag/country-sz.svg'),
            ],
            [
                'sort' => 'SE',
                'country_name' => 'Sweden',
                'phoneCode' => 46,
                'flag'=>asset('country-flag/country-se.svg'),
            ],
            [
                'sort' => 'CH',
                'country_name' => 'Switzerland',
                'phoneCode' => 41,
                'flag'=>asset('country-flag/country-ch.svg'),
            ],
            [
                'sort' => 'SY',
                'country_name' => 'Syria',
                'phoneCode' => 963,
                'flag'=>asset('country-flag/country-sy.svg'),
            ],
            [
                'sort' => 'TW',
                'country_name' => 'Taiwan',
                'phoneCode' => 886,
                'flag'=>asset('country-flag/country-tw.svg'),
            ],
            [
                'sort' => 'TJ',
                'country_name' => 'Tajikistan',
                'phoneCode' => 992,
                'flag'=>asset('country-flag/country-tj.svg'),
            ],
            [
                'sort' => 'TZ',
                'country_name' => 'Tanzania',
                'phoneCode' => 255,
                'flag'=>asset('country-flag/country-tz.svg'),
            ],
            [
                'sort' => 'TH',
                'country_name' => 'Thailand',
                'phoneCode' => 66,
                'flag'=>asset('country-flag/country-th.svg'),
            ],
            [
                'sort' => 'TG',
                'country_name' => 'Togo',
                'phoneCode' => 228,
                'flag'=>asset('country-flag/country-tg.svg'),
            ],
            [
                'sort' => 'TK',
                'country_name' => 'Tokelau',
                'phoneCode' => 690,
                'flag'=>asset('country-flag/country-tk.svg'),
            ],
            [
                'sort' => 'TO',
                'country_name' => 'Tonga',
                'phoneCode' => 676,
                'flag'=>asset('country-flag/country-to.svg'),
            ],
            [
                'sort' => 'TT',
                'country_name' => 'Trincountry_idad And Tobago',
                'phoneCode' => 1868,
                'flag'=>asset('country-flag/country-tt.svg'),
            ],
            [
                'sort' => 'TN',
                'country_name' => 'Tunisia',
                'phoneCode' => 216,
                'flag'=>asset('country-flag/country-tn.svg'),
            ],
            [
                'sort' => 'TR',
                'country_name' => 'Turkey',
                'phoneCode' => 90,
                'flag'=>asset('country-flag/country-tr.svg'),
            ],
            [
                'sort' => 'TM',
                'country_name' => 'Turkmenistan',
                'phoneCode' => 7370,
                'flag'=>asset('country-flag/country-tm.svg'),
            ],
            [
                'sort' => 'TC',
                'country_name' => 'Turks And Caicos Islands',
                'phoneCode' => 1649,
                'flag'=>asset('country-flag/country-tc.svg'),
            ],
            [
                'sort' => 'TV',
                'country_name' => 'Tuvalu',
                'phoneCode' => 688,
                'flag'=>asset('country-flag/country-tv.svg'),
            ],
            [
                'sort' => 'UG',
                'country_name' => 'Uganda',
                'phoneCode' => 256,
                'flag'=>asset('country-flag/country-ug.svg'),
            ],
            [
                'sort' => 'UA',
                'country_name' => 'Ukraine',
                'phoneCode' => 380,
                'flag'=>asset('country-flag/country-ua.svg'),
            ],
            [
                'sort' => 'AE',
                'country_name' => 'United Arab Emirates',
                'phoneCode' => 971,
                'flag'=>asset('country-flag/country-ae.svg'),
            ],
            [
                'sort' => 'GB',
                'country_name' => 'United Kingdom',
                'phoneCode' => 44,
                'flag'=>asset('country-flag/country-gb.svg'),
            ],
            [
                'sort' => 'US',
                'country_name' => 'United States',
                'phoneCode' => 1,
                'flag'=>asset('country-flag/country-us.svg'),
            ],
            [
                'sort' => 'UM',
                'country_name' => 'United States Minor Outlying Islands',
                'phoneCode' => 1,
                'flag'=>asset('country-flag/country-um.svg'),
            ],
            [
                'sort' => 'UY',
                'country_name' => 'Uruguay',
                'phoneCode' => 598,
                'flag'=>asset('country-flag/country-uy.svg'),
            ],
            [
                'sort' => 'UZ',
                'country_name' => 'Uzbekistan',
                'phoneCode' => 998,
                'flag'=>asset('country-flag/country-uz.svg'),
            ],
            [
                'sort' => 'VU',
                'country_name' => 'Vanuatu',
                'phoneCode' => 678,
                'flag'=>asset('country-flag/country-vu.svg'),
            ],
            [
                'sort' => 'VA',
                'country_name' => 'Vatican City State (Holy See)',
                'phoneCode' => 39,
                'flag'=>asset('country-flag/country-va.svg'),
            ],
            [
                'sort' => 'VE',
                'country_name' => 'Venezuela',
                'phoneCode' => 58,
                'flag'=>asset('country-flag/country-ve.svg'),
            ],
            [
                'sort' => 'VN',
                'country_name' => 'Vietnam',
                'phoneCode' => 84,
                'flag'=>asset('country-flag/country-vn.svg'),
            ],
            [
                'sort' => 'VG',
                'country_name' => 'Virgin Islands (British)',
                'phoneCode' => 1284,
                'flag'=>asset('country-flag/country-vg.svg'),
            ],
            [
                'sort' => 'VI',
                'country_name' => 'Virgin Islands (US)',
                'phoneCode' => 1340,
                'flag'=>asset('country-flag/country-vi.svg'),
            ],
            [
                'sort' => 'WF',
                'country_name' => 'Wallis And Futuna Islands',
                'phoneCode' => 681,
                'flag'=>asset('country-flag/country-wf.svg'),
            ],
            [
                'sort' => 'EH',
                'country_name' => 'Western Sahara',
                'phoneCode' => 212,
                'flag'=>asset('country-flag/country-eh.svg'),
            ],
            [
                'sort' => 'YE',
                'country_name' => 'Yemen',
                'phoneCode' => 967,
                'flag'=>asset('country-flag/country-ye.svg'),
            ],
            [
                'sort' => 'YU',
                'country_name' => 'Yugoslavia',
                'phoneCode' => 38,
                'flag'=>asset('country-flag/country-yu.svg'),
            ],
            [
                'sort' => 'ZM',
                'country_name' => 'Zambia',
                'phoneCode' => 260,
                'flag'=>asset('country-flag/country-zm.svg'),
            ],
            [
                'sort' => 'ZW',
                'country_name' => 'Zimbabwe',
                'phoneCode' => 26,
                'flag'=>asset('country-flag/country-zw.svg'),
            ],
        );


        return $payment;
    }
}
